export const GET_COFFEE_REQUEST = "GET_COFFEE_REQUEST";
export const GET_COFFEE_SUCCESS = "GET_COFFEE_SUCCESS";
export const GET_COFFEE_FAILURE = "GET_COFFEE_FAILURE";

export const GET_EMPLOYEE_REQUEST = "GET_EMPLOYEE_REQUEST";
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEE_FAILURE = "GET_EMPLOYEE_FAILURE";

export const GET_RESTAURANT_REQUEST = "GET_RESTAURANT_REQUEST";
export const GET_RESTAURANT_SUCCESS = "GET_RESTAURANT_SUCCESS";
export const GET_RESTAURANT_FAILURE = "GET_RESTAURANT_FAILURE";


